name: Main Workflow

on: [push]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build
      run: ./Build.ps1 -NoTest
      shell: pwsh

    - name: Test
      run: ./Test.ps1
      shell: pwsh