name: Main Workflow

on: [push]

jobs:
  Ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Build
      run: ./Build.ps1 -NoTest -ResolveDependency
      shell: pwsh

    - name: Test
      run: ./Test.ps1
      shell: pwsh